# -*- coding: utf-8 -*-
"""ExamML Шелепов_A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XT58_Hcbn5DXoRxez_pyTy95pn3oOWK

# Модуль A

## Предобработка данных
"""

import pandas as pd

data = pd.read_csv('MaintenanceR.csv')
data

data = data.drop(['Unnamed: 14'], axis=1)
data.info()

"""Проверка на пропуски"""

data.isna().sum()

"""Пропусков в данных нет

Проверим данные на дубликаты
"""

data = data.drop_duplicates()
data

"""Дубликатов нет

Изменим типы столбцов Air temperature [K],	Process temperature [K] и Torque [Nm] на float
"""

cols_to_float = ['Air temperature [K]',	'Process temperature [K]', 'Torque [Nm]']
for c in cols_to_float:
  col_values = data[c].to_list()
  new_col_values = []
  for v in col_values:
    new_col_values.append(float(v.replace(',', '.')))
  data[c] = new_col_values

data.info()

"""Заменим значения type на числа: H: 0, L: 1, M: 2"""

data['Type'] = data['Type'].replace({'H': 0, 'L': 1, 'M': 2})
data['Type']

"""## Исследовательский анализ данных

Обработка выбросов
"""

from matplotlib import pyplot as plt

cols = ['Air temperature [K]',	'Process temperature [K]',	'Torque [Nm]']
for c in cols:
  data.hist(c, log=True, bins=20)

"""Данные распределены нормально.

Выбросы наблюдаются в Air Temperature, Process Temperature
"""

data_with_outliers = data[['Air temperature [K]',	'Process temperature [K]']]

q1 = data_with_outliers.quantile(0.25)
q3 = data_with_outliers.quantile(0.75)

iqr = q3 - q1

data_filtered = data[~((data_with_outliers < q1 - 1.5 * iqr) | (data_with_outliers > q3 + 1.5 * iqr)).any(axis=1)]

data_filtered

"""Гистограммы данных без выбросов"""

cols = ['Air temperature [K]',	'Process temperature [K]']
for c in cols:
  data_filtered.hist(c, log=True, bins=20)

data_filtered.describe()

"""Рассмотрим, насколько сильно зависит целевая переменная Rotational Speed от различных признаков"""

import seaborn as sns

float_cols = ['Air temperature [K]',	'Process temperature [K]',	'Torque [Nm]',	'Tool wear [min]']

for c in float_cols:
  sns.lmplot(data_filtered[:1000], x=c, y='Rotational speed [rpm]')

""" Очевидно, что наибольшее влияние на скорость вращения оказывает крутящий момент.

 Остальные вещественные признаки практически не влияют на скорость вращения.
"""

cat_cols = ['Type', 'Machine failure',	'TWF',	'PWF',	'OSF']

for c in cat_cols:
  data_filtered[:1000].boxplot(by=c, column='Rotational speed [rpm]')

"""Заметим, что уменьшение крутящего момента чаще всего возникает из-за поломки машины в целом, отказа питания и перенапряжения.

Столбцы RNF и HDF не учитывались, так как после удаления выбросов все значения этих столбцов стали равны 0.

Корреляция между числовыми признаками:
"""

сols_to_float_corr = ['Air temperature [K]',	'Process temperature [K]',	'Rotational speed [rpm]',	'Torque [Nm]',	'Tool wear [min]']
data_to_float_corr = data[сols_to_float_corr]

sns.heatmap(data_to_float_corr.corr(method='spearman'), annot = True, cmap='coolwarm')

"""Корреляция между числовыми/категориальными признаками:"""

сols_to_int_corr = ['Rotational speed [rpm]', 'Type', 'Machine failure',	'TWF',	'PWF',	'OSF']
data_to_int_corr = data[сols_to_int_corr]

sns.heatmap(data_to_int_corr.corr(method='kendall'), annot = True, cmap='coolwarm')

data_filtered.to_csv('rotation_prepared.csv')